version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - urna-db:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  urna-db:
